Fix tests for 3.1.7 (#83)
* Fix test error on schema caused by pgtap bug

Bug reported to pgtap upstream here:

  https://github.com/theory/pgtap/pull/311

* Test minimal postgresql supported version

* Fix test failing because of objects order

the test can fail when running the test on a database with
a different collation than the one used to write the test.

* Fix SQL error with pg 16

* Fix test errors with pg_read_all_data and pg_write_all_data roles

* Update pgsodium version in test generator

* Add tests about masking_rule.security_invoker column

* Comply tests generator and SQL schema to the new test.sql script

* Create role and extension inside the test's transaction

* Create pgsodium extension outside of the transaction

When creating the extension inside the xact, one test is failing with
the following error:

  ERROR:  unsafe use of new value "secretbox" of enum type key_type
  LINE 1: SELECT id as secretbox_key_id from create_key('secretbox')
                                                      ^
  HINT:  New enum values must be committed before they can be used

* Make volumes accessible inside the container with podman